CREATE TABLE IF NOT EXISTS T_USER(
ID INTEGER (5) AUTO_INCREMENT NOT NULL ,
EMAIL VARCHAR (20) NOT NULL,
PASSWORD VARCHAR (20) NOT NULL ,
FIRST_NAME VARCHAR (20) NOT NULL ,
LAST_NAME VARCHAR (20) NOT NULL ,
PRIMARY KEY(ID)
)